### ISSUE TITLE
Điều chỉnh tốc độ

### ISSUE THREAD

**Issue by UIT-22730099** [UIT-22730104/snakegame-atvteam#31]
Mình cảm thấy tốc độ con rắn khi di chuyển lên và xuống nhanh hơn so với đi ngang, có cách nào fix không ạ?

**Comment by UIT-22730104** [comment]
Đây thật ra không phải là lỗi đâu Trúc. Do trò chơi chạy trên màn hình console và mỗi 1 ô pixel như vậy có dạng hình chữ nhật đứng nên về mặt hiển thị thì tốc độ sẽ không đồng đều. Mình có 2 hướng đề xuất để giải quết là:

1. Tăng thời gian sleep khi di chuyển theo phương ngang, căn chỉnh sao cho bằng với phương dọc
2. Mỗi bước di chuyển của con rắn khi đi theo phương ngang sẽ là 2 pixel thay vì 1
