### ISSUE TITLE
Lập hợp đồng nhóm

### ISSUE THREAD

**Issue by UIT-22730104** [UIT-22730104/snakegame-atvteam#4]
- @UIT-22730099 (Trúc) soạn thảo hợp đồng (yêu cầu sử dụng Latex).
- @UIT-22730104 (Vinh) chỉnh sửa, bổ sung (nếu có).

**Comment by UIT-22730104** [comment]
> Mình soạn xong "Hợp đồng nhóm" rồi, mọi người xem và góp ý những chỗ cần chỉnh sửa để bài hoàn thiện hơn nha. Cảm ơn mọi người !
> 
> [hdn_ss04(done).pdf](https://github.com/UIT-22730104/snakegame-atvteam/files/12093458/hdn_ss04.done.pdf)

Mình thấy hợp đồng của Trúc soạn quá tốt, mình xin phép góp ý thêm một số điểm sau:

- Không nên đánh trang bìa là trang số 1
- Ở trang 2, Trúc nên bổ sung tên đơn vị trực thuộc + Quốc hiệu  + Tên hợp đồng nha

**Comment by UIT-22730104** [comment]
Cảm ơn Trúc. Nhóm mình lần lượt tải file về và ký tên vào nha, sau đó upload file đã ký tên lên cho người tiếp theo ký tên nha.
Mình đã ký tên, tiếp theo mọi người có thể ký lên file này: 
[atvteam-hopdongnhom.pdf](https://github.com/UIT-22730104/snakegame-atvteam/files/12110248/atvteam-hopdongnhom.pdf)

**Comment by UIT-22730106** [comment]
Đã ký 

[atvteam-hopdongnhom.pdf](https://github.com/UIT-22730104/snakegame-atvteam/files/12124581/atvteam-hopdongnhom.pdf)

**Comment by UIT-22730104** [comment]
@UIT-22730099 Trúc lưu lại file đã ký đầy đủ nhé. Mình đóng issue này ở đây. Cám ơn mọi người rất nhiều.

**Comment by UIT-22730104** [comment]
[atvteam-hopdongnhom.pdf](https://github.com/UIT-22730104/snakegame-atvteam/files/12138646/atvteam-hopdongnhom.pdf)
